name: First Workflow
on: push
jobs: 
    checkout-code: 
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: 24
            - name: Install dependencies
              run: npm ci
              working-directory: ./practice-project-4
            - name: Lint code
              run: npm run lint
              working-directory: ./practice-project-4
            - name: Test code
              run: npm test
              working-directory: ./practice-project-4
            - name: Build code
              run: npm run build
              working-directory: ./practice-project-4
    deployment:
        needs: checkout-code
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install dependencies
              run: npm ci
              working-directory: ./practice-project-4
            - name: Build code
              run: npm run build
              working-directory: ./practice-project-4
            - name: Deploy to Server
              run: echo "Deploying to server"
